### ISSUE TITLE
New cogwheel

### ISSUE THREAD

**Issue by albertosaurio65** [Rabbitminers/Extended-Cogwheels#20]
Maybe add more cogwheels, like brass, gold, stone, etc. Also metal from other mods like immersive engineering or tinker.

Also new shaft of another materiales, and enable this 
![image](https://user-images.githubusercontent.com/70109413/218330150-d6502fef-2841-43c8-9dba-a7518a6cdc19.png)

**Comment by Rabbitminers** [comment]
Im not sure about stone but some other materials are definitely planned and should be much quicker to implement with the overhauled datagen systems
